# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "060ad597ef97d7bda7acdb03e9f97bd5"
application_url = "https://replace-ppc-ah-exchange.trycloudflare.com"
embedded = true
name = "Reviews: Import & Display"
handle = "reviews-import-and-display"

[build]
include_config_on_deploy = true
dev_store_url = "dev-reviews-ftu.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://replace-ppc-ah-exchange.trycloudflare.com/auth/callback", "https://replace-ppc-ah-exchange.trycloudflare.com/auth/shopify/callback", "https://replace-ppc-ah-exchange.trycloudflare.com/api/auth/callback"]

[pos]
embedded = true
